language: go

sudo: required

os:
    - linux
    - osx

go:
  - 1.9
  - 1.10.x
  - 1.11.x

env:
  global:
    - secure: "gqE0nDOmyBquhQ4JrgngseYtol1QlGGwg4QfomLDi08N60ONxJqo1f3JAqFgQMAfRGg8wz7QdSeL/oiJv9bkXj5hxN/zd8vPNFaOG1yBK3lbr15CekrhlGEYGIPiVoM8YnFtsiwFj1MH+9R4tCTCnN2ybqOk0UvKJA0Ty7m+XLGffV6Cdzlzqi+3zmsCPbxxk7f1w+xK5g6NiFHXTbi1z1IJ9aSluXEcqgEH1uWP9xjaU/P+85bFUOqMoOHXajyzuFOwdTNAhdTIoEWkPHUpOorcboudFCqDKaVJbwQYtpm1cNEtuzd26DZFCU1c4C+MSJfMGdPYqCcjziCHWjpp2Q1pJM6+hSQHeZnehu9Z2kRB0TySOKZIolVkwMU4ZV9ordS5p29jTAeHE3K0jwUzz2PLqUp4kASgo7DmidAzlClqtvhOHKm/OgI4CgUm/+AD0ZVlUnNPlMzEnuzS9XCvrp+WBYEGqzfZAHMgGK2KylA9uBz/h3f5V1lQUJUp/Rqz2AEzy7a4cdPeSZfHd1BWZB9yOvKEgr5cOP1vmKCDEYvsPRC5EkP9fgydZSb2l/1ZLpWjyjs9dwz0lkb3doFgYap5xHXHYJ7rs9v3BQZF3d8x1yMfmvhR1dcs315K+iYGTn5YY9k7JEskpdIEJTBM48/ElLb69cwA9eoJIqUfpHU="
    - QINIU_KODO_TEST=1
    - accessKey=vHg2e7nOh7Jsucv2Azr5FH6omPgX22zoJRWa0FN5
    - QINIU_TEST_BUCKET=gosdk
    - QINIU_TEST_BUCKET_PRIVATE=gosdk.qiniudn.com
    - QINIU_TEST_DOMAIN=gosdk.qiniudn.com
    - QINIU_TEST_DOMAIN_PRIVATE=gosdk.qiniudn.com
    - QINIU_TEST_PIPELINE=sdktest
install:
  go get github.com/qiniu/x

script:
  - make test

branches:
  only:
    - master
