language: go
go:
  - 1.7
  - 1.8
  - master
env:
  global:
    - QINIU_KODO_TEST=1

install:
  - export QINIU_SRC=$HOME/gopath/src
  - mkdir -p $QINIU_SRC/github.com/tonycai653
  - go get github.com/tonycai653/x
